pipeline{
    agent any

    tools{
        maven 'Maven3'
    }

    stages{
        stage('Build'){
            steps{
                echo 'Building Project..'

                sh 'mvn clean package'
            }
        }
    }
}