pipeline{
    agent any

    tools{
        maven 'Maven3'
    }

    stages{
        stage('Build'){
            steps{
                echo 'Building Project..'
                dir('jenkins-maven-demo'){
                sh 'mvn clean package'
                }
            }
        }
    }
}